### ISSUE TITLE
[ERROR] null when running Cluster Analysis BETA v2

### ISSUE THREAD

**Issue by colameo** [dcolam/Cluster-Analysis-Plugin#3]
Free Memory  221MB of 8368MB (2%)
Current Memory 260122672
Analysing image:  1a_CT12BL_Syt1_CA3_40x0.7_710.lsm
Reading LSM metadata for series #0
[WARN] Unknown LaserMedium value '' will be stored as "Other"
[WARN] Unknown LaserType value 'DPSS 561-10' will be stored as "Other"
[WARN] Unknown LaserMedium value '' will be stored as "Other"
[WARN] Unknown LaserType value 'Diode 405-30' will be stored as "Other"
Selection1
ZStacked
______________________________________________
Measurement of Selection1
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Selection1-Increment1
ZStacked
______________________________________________
Measurement of Selection1-Increment1
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Selection1-Increment2
ZStacked
______________________________________________
Measurement of Selection1-Increment2
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Selection1-Increment3
ZStacked
______________________________________________
Measurement of Selection1-Increment3
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Selection1-Increment4
ZStacked
______________________________________________
Measurement of Selection1-Increment4
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Selection1-inversed
ZStacked
______________________________________________
Measurement of Selection1-inversed
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
allSelected
ZStacked
______________________________________________
Measurement of allSelected
Threshold Method: Huang, Max: 255.0, Min: 11.0
4385
Corrected:  56.8658777549 5686.58777549 56.8658777549 5686.58777549
Raw:  5.0 500.0 16.8620695282 1686.20695282
Number of entries:  7
Particle Analysis Data inserted successfully
*****************************************************
Current Memory Free Memory  245MB of 8368MB (2%)
260772480
Number of images analyzed:  1
It took 7.33500003815 seconds.
[ERROR] null
Traceback (most recent call last):
  File "Cluster_Analysis/ImageJ2/Cluster_Analysis_BETA_v2.py", line 2129, in <module>
SystemExit: 0

	at org.python.core.PySystemState.exit(PySystemState.java:1494)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx0.f$0(Cluster_Analysis/ImageJ2/Cluster_Analysis_BETA_v2.py:2129)
	at org.python.pycode._pyx0.call_function(Cluster_Analysis/ImageJ2/Cluster_Analysis_BETA_v2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dcolam** [comment]
The script will end with a sys.exit(0) in headless-mode, if everything went right. This behaviour is expected and right.
